### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by Gyuhex** [Gyuhex/dojo-vault#25]
**Description**: Implement user registration, login, and session management with Firebase Authentication.

### Tasks:
- [ ] Set up registration form for creating users via Firebase Authentication.
- [ ] Set up login form to authenticate users.
- [ ] Use Firebase’s `onAuthStateChanged` to track user login state.
- [ ] Redirect users based on authentication state (logged in vs logged out).
