### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Gyuhex** [Gyuhex/dojo-vault#28]
**Description**: Test Firebase Authentication and Firestore functionality to ensure everything works.

### Tasks:
- [ ] Test user registration functionality.
- [ ] Test user login functionality.
- [ ] Test Firestore add, edit, and delete functions.
- [ ] Test real-time Firestore data updates.
- [ ] Test app behavior for authenticated and unauthenticated users.
