### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Gyuhex** [Gyuhex/dojo-vault#29]
**Description**: Deploy the app with Firebase Authentication and Firestore integration.

### Tasks:
- [ ] Ensure features work properly in production.
- [ ] Deploy the app to a hosting platform like Firebase Hosting.
- [ ] Test the deployed app in the live environment.
